version: 2.1

#ここに指定しているものは繰り返しすかうことができる。
anchor:
  hello_place_anchor: &hello_place_anchor
    parameters:
      env:
        type: enum
        enum: ["Osaka", "Tokyo", "Nagoya"]
        default: "Osaka"
    steps:
      - run:
          command: echo Hello, << parameters.env >>
#処理の順序を指定
workflows:
  hello_direct:
    jobs:
      - hello_direct
  hello_use_executor:
    jobs:
      - hello_use_executor
  hello_use_parameter:
    jobs:
      - hello_use_parameter
  hello_exexutor_commnad:
    jobs:
      - hello_use_executor_command
  hello_enum:
    jobs:
      - hello_use_executor_command_enum:
          name: echo_Osaka
          env: "Osaka"
  hello_use_anchor:
    jobs:
      - hello_use_anchor:
          name: echo_tokyo
          env: "Tokyo"

#アンカーと同じ繰り返し使える。指定する範囲が違う。基本的に一つの変数を設定する
parameters:
  echoplacename:
    type: string
    default: "Okinawa"

#アンカーと同じ繰り返し使える。指定する範囲が違う。環境を指定する。
executors:
  hello_executor:
    docker:
      - image: cimg/base:<<parameters.tag>>
    parameters:
      tag:
        default: "2021.07"
        type: string
#アンカーと同じ繰り返し使える。指定する範囲が違う。stepsに関連した内容を保存
commands:
  hello_generic_cmd:
    parameters:
      placeName:
        default: "test"
        type: string
    steps:
      - run: echo Hello, <<parameters.placeName>>

#処理の内容を記述する。
jobs:
  hello_direct:
    docker:
        - image: cimg/base:2021.07
    steps:
      - run: echo Hello, "direct"
  
  hello_use_executor:
    executor:
      name: hello_executor
    steps:
      - run: echo Hello, "Osaka"
  hello_use_parameter:
    docker:
        - image: cimg/base:2021.07
    steps:
      - run: echo Hello, <<pipeline.parameters.echoplacename>>
  
  hello_use_executor_command:
    executor: hello_executor
    steps:
      - hello_generic_cmd:
          placeName: "tokyo"
          
          
  hello_use_executor_command_enum:
    parameters:
      env:
        type: enum
        enum: ["Osaka", "Tokyo", "Nagoya"]
        default: "Osaka"
    executor:
      name: hello_executor
    steps:
      - run:
          command: echo Hello, << parameters.env >>
  
  hello_use_anchor:
    <<: *hello_place_anchor
    executor:
      name: hello_executor
