version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "deploy my app"
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "test my app"
workflows:
  test-and-deploy:
    jobs:
      - test
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow
