version: 2.1

workflows:
  hello_place:
    jobs:
      - hello_tokyo
      - hello_osaka

executors:
  hello_executor:
    docker:
      - image: cimg/base:<<parameters.tag>>
    parameters:
      tag:
        type: string

commands:
  hello_generic_cmd:
    parameters:
      placeName:
        type: string
    steps:
      - run: echo Hello, <<parameters.placeName>>

jobs:
  hello_tokyo:
    executor: 
      name: hello_executor
      parameters:
        tag: "2021.08"
    steps:
      - checkout
      - hello_generic_cmd:
          placeName: "tokyo"
          
  hello_osaka:
    executor: hello_executor
    steps:
      - checkout
      - hello_generic_cmd:
          placeName: "osaka"


