version: 2.1
commands:

    notify:
        description: |
            Notify a Slack channel with a custom message.
            The environment variables SLACK_ACCESS_TOKEN and SLACK_DEFAULT_CHANNEL must be set for this orb to work.
            For instructions on how to set them, follow the setup guide available in the wiki: https://github.com/CircleCI-Public/slack-orb/wiki/Setup.
        parameters:
            branch_pattern:
                default: .+
                description: |
                    A comma separated list of regex matchable branch names. Notifications will only be sent if sent from a job from these branches. By default ".+" will be used to match all branches. Pattern must match the full string, no partial matches.
                type: string
            channel:
                default: $SLACK_DEFAULT_CHANNEL
                description: |
                    Select which channel in which to post to. Channel name or ID will work. You may include a comma separated list of channels if you wish to post to multiple channels at once. Set the "SLACK_DEFAULT_CHANNEL" environment variable for the default channel.
                type: string
            circleci_host:
                default: https://circleci.com
                description: |
                    A CircleCI Host which used in a message template.
                type: string
            custom:
                default: ""
                description: |
                    Enter a custom message template.

                    1. Create your message template using the Block Kit Builder: https://app.slack.com/block-kit-builder/.
                    2. Insert any desired environment variables.
                    3. Paste value here.
                type: string
            debug:
                default: false
                description: |
                    Enable to view full payload being sent to Slack and response being received from the API call.
                    Redacted content can be viewed by re-running the job with SSH and accessing the log files referenced in the job output.
                    When run in a persistent build environment such as CircleCI Runner, these debug log files may remain in the system's temporary filesystem indefinitely and accumulate over time.
                type: boolean
            event:
                default: always
                description: |
                    In what event should this message send? Options: ["fail", "pass", "always"]
                enum:
                    - fail
                    - pass
                    - always
                type: enum
            ignore_errors:
                default: true
                description: |
                    Ignore errors posting to Slack.
                    Disable to catch initial setup errors. Re-enable to prevent Slack errors from affecting your pipeline.
                type: boolean
            invert_match:
                default: false
                description: |
                    Invert the branch and tag patterns.
                    If set to true, notifications will only be sent if sent from a job from branches and tags that do not match the patterns.
                type: boolean
            mentions:
                default: ""
                description: |
                    Exports to the "$SLACK_PARAM_MENTIONS" environment variable for use in templates.
                    Mention users via the @ symbol: "@USER"
                    If the username contains a space, the Slack ID must be used with angled brackets: "<@U8XXXXXXX>"
                type: string
            step_name:
                default: Slack - Sending Notification
                description: Specify a custom step name for this command, if desired
                type: string
            tag_pattern:
                default: .+
                description: |
                    A comma separated list of regex matchable tag names. Notifications will only be sent if sent from a job from these branches. By default ".+" will be used to match all tags. Pattern must match the full string, no partial matches.
                type: string
            template:
                default: ""
                description: |
                    Select which template to use for the notification by its name. The name must be available as an environment variable.
                    The built-in templates can be found and previewed at: https://github.com/CircleCI-Public/slack-orb/wiki#templates.
                    Alternatively, you can create and use your own dynamic templates: https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates.
                    If left empty and no custom template is provided, the template will be automatically selected based on the job status.
                type: string
        steps:
            - run:
                command: |
                    echo 'export CCI_STATUS="fail"' > /tmp/SLACK_JOB_STATUS
                name: Slack - Detecting Job Status (FAIL)
                when: on_fail
            - run:
                command: |
                    echo 'export CCI_STATUS="pass"' > /tmp/SLACK_JOB_STATUS
                name: Slack - Detecting Job Status (PASS)
                when: on_success

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - notify
workflows:
  test-command:
    jobs:
      - myjob:
          context: slack-secrets
