version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "checkboxes",
                      "options": [
                        {
                          "text": {
                            "type": "plain_text",
                            "text": "*this is plain_text text*",
                            "emoji": true
                          },
                          "description": {
                            "type": "plain_text",
                            "text": "*this is plain_text text*",
                            "emoji": true
                          },
                          "value": "value-0"
                        },
                        {
                          "text": {
                            "type": "plain_text",
                            "text": "*this is plain_text text*",
                            "emoji": true
                          },
                          "description": {
                            "type": "plain_text",
                            "text": "*this is plain_text text*",
                            "emoji": true
                          },
                          "value": "value-1"
                        },
                        {
                          "text": {
                            "type": "plain_text",
                            "text": "*this is plain_text text*",
                            "emoji": true
                          },
                          "description": {
                            "type": "plain_text",
                            "text": "*this is plain_text text*",
                            "emoji": true
                          },
                          "value": "value-2"
                        }
                      ],
                      "action_id": "actionId-0"
                    },
                    {
                      "type": "checkboxes",
                      "options": [
                        {
                          "text": {
                            "type": "mrkdwn",
                            "text": "*this is mrkdwn text*"
                          },
                          "description": {
                            "type": "mrkdwn",
                            "text": "*this is mrkdwn text*"
                          },
                          "value": "value-0"
                        },
                        {
                          "text": {
                            "type": "mrkdwn",
                            "text": "*this is mrkdwn text*"
                          },
                          "description": {
                            "type": "mrkdwn",
                            "text": "*this is mrkdwn text*"
                          },
                          "value": "value-1"
                        },
                        {
                          "text": {
                            "type": "mrkdwn",
                            "text": "*this is mrkdwn text*"
                          },
                          "description": {
                            "type": "mrkdwn",
                            "text": "*this is mrkdwn text*"
                          },
                          "value": "value-2"
                        }
                      ],
                      "action_id": "actionId-1"
                    }
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
