version: 2.1

my-anchorjob: &my-anchorjob
  docker:
    - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
  parameters:
    my-hello-word:
      type: string
      default: "sample hello"
  steps:
    - checkout # check out the code in the project directory
    - run: echo <<pipeline.parameters.my-hello-word>>

parameters:
  hello-word:
    type: string
    default: "Hello World"

jobs:
  hello-job1:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  hello-job2:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo <<pipeline.parameters.hello-word>>
  hello-job3:
    <<: *my-anchorjob
workflows:
  my-workflow:
    jobs:
      - hello-job1
      - hello-job2
      - hello-job3
