version: 2.1

workflows:
  hello_direct:
    jobs:
      - hello_direct
  hello_place:
    jobs:
      - hello_tokyo
      - hello_osaka
      - hello_test
  deployplace:
    jobs:
      - echo_deploy_enviroment:
          name: deploy_dev
          env: "stg"

parameters:
  echosamplename:
    type: string
    defualt: "Okinawa"

executors:
  hello_executor:
    docker:
      - image: cimg/base:<<parameters.tag>>
    parameters:
      tag:
        default: "2021.07"
        type: string

commands:
  hello_generic_cmd:
    parameters:
      placeName:
        default: "test"
        type: string
    steps:
      - run: echo Hello, <<parameters.placeName>>

jobs:
  hello_direct:
    docker:
        - image: cimg/base:2021.07
    steps:
      - run: echo Hello, "direct"
        
  hello_tokyo:
    executor: hello_executor
    steps:
      - hello_generic_cmd:
          placeName: "tokyo"
          
  hello_osaka:
    executor: hello_executor
    steps:
      - checkout
      - hello_generic_cmd:
          placeName: "osaka"
  hello_test:
    executor: hello_executor
    steps:
      - checkout
      - hello_generic_cmd
  echo_deploy_enviroment:
    parameters:
      env:
        type: enum
        enum: ["dev", "stg", "prod"]
        default: "dev"
    executor:
      name: hello_executor
    steps:
      - checkout
      - run:
          command: echo Deploy to << parameters.env >> environment


