version: 2.1
orbs:
    # このワークフローでは、shellcheckとslackのふたつのOrbを利用する
  shellcheck: circleci/shellcheck@3.0.0
  slack: circleci/slack@4.8.1

jobs:
  test:
    docker:
      # CIジョブを実行するコンテナイメージは、CircleCIのベースイメージ
      - image: 'cimg/base:2022.02'
    steps:
      # コードのチェックアウト
      - checkout

      # shellcheckを実行する
      - shellcheck/check:
          dir: ./
          pattern: '*.sh'

      # shellcheckが失敗した場合(event: fail)に失敗通知を送信する
      - slack/notify:
          template: basic_fail_1
          event: fail

      # shellcheckが成功した場合(event: pass)に成功通知を送信する
      - slack/notify:
          template: basic_success_1
          event: pass
workflows:
  my_workflow:
    jobs:
      - test:
          # このジョブでslack-tokenコンテキストを利用する
          context: slack-secrets
