
version: 2.1
jobs:
  on-hold:
    description: |
      Insert this job in-line with your standard CircleCI on-hold notification jobs to simulataniously send a Slack notification containing a link to the paused Workflow.
    docker:
      - image: cimg/base:stable
    parameters:
      branch_pattern:
        default: .+
        description: |
          A comma separated list of regex matchable branch names.
          Notifications will only be sent if sent from a job from these branches.
          By default ".+" will be used to match all branches. Pattern must be a POSIX expression and match the full string, no partial matches.
        type: string
      channel:
        default: $SLACK_DEFAULT_CHANNEL
        description: |
          Select which channel in which to post to. Channel name or ID will work. You may include a comma separated list of channels if you wish to post to multiple channels at once. Set the "SLACK_DEFAULT_CHANNEL" environment variable for the default channel.
        type: string
      circleci_host:
        default: https://circleci.com
        description: |
          CircleCI Host (used as the base for the Workflow URL)
        type: string
      custom:
        default: ""
        description: |
          (optional) Enter a custom message template.

          1. Create your message template using the Block Kit Builder: https://app.slack.com/block-kit-builder/.
          2. Insert any desired environment variables.
          3. Paste value here.
        type: string
      debug:
        default: false
        description: |
          View payload and response being sent to slack api.
          Enable to view full payload being sent to slack and response being received from the API call.
        type: boolean
      invert_match:
        default: false
        description: |
          Invert the branch and tag patterns.
          If set to true, notifications will only be sent if sent from a job from branches and tags that do not match the patterns.
        type: boolean
      mentions:
        default: ""
        description: |
          Exports to the "$SLACK_PARAM_MENTIONS" environment variable for use in templates.
          Mention users via the @ symbol: "@USER"
          If the username contains a space, the Slack ID must be used with angled brackets: "<@U8XXXXXXX>"
        type: string
      step_name:
        default: Slack - Sending Notification
        description: Specify a custom step name for this command, if desired
        type: string
      template:
        default: basic_on_hold_1
        description: (optional) By default this job will send the standard "basic_on_hold_1" template. In order to use a custom template you must also set this value to an empty string.
        type: string
    resource_class: small
    steps:
      - notify:
        branch_pattern: <<parameters.branch_pattern>>
        channel: <<parameters.channel>>
        circleci_host: <<parameters.circleci_host>>
        custom: <<parameters.custom>>
        debug: <<parameters.debug>>
        event: always
        invert_match: <<parameters.invert_match>>
        mentions: <<parameters.mentions>>
        step_name: <<parameters.step_name>>
        template: <<parameters.template>>
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - notify:
        custom: |
          {
            "blocks": [
            {
              "type": "section",
              "fields": [
              {
                "type": "plain_text",
                "text": "*This is a text notification*",
                "emoji": true
              }
              ]
            }
            ]
          }
        event: always
workflows:
  send-notification:
    jobs:
      - notify:
        context: slack-secrets
