version: 2.1

workflows:
  hello_place:
    jobs:
      - hello_tokyo
      - hello_osaka
      - hello_test

executors:
  hello_executor:
    docker:
      - image: cimg/base:<<parameters.tag>>
    parameters:
      tag:
        default: "2021.07"
        type: string

commands:
  hello_generic_cmd:
    parameters:
      placeName:
        default: "test"
        type: string
    steps:
      - run: echo Hello, <<parameters.placeName>>

jobs:
  hello_tokyo:
    executor: hello_executor
      tag: "2021.08"
    steps:
      - checkout
      - hello_generic_cmd:
          placeName: "tokyo"
          
  hello_osaka:
    executor: hello_executor
    steps:
      - checkout
      - hello_generic_cmd:
          placeName: "osaka"
  hello_test:
    executor: hello_executor
    steps:
      - checkout
      - hello_generic_cmd


