version: 2.1

anchor:
  hello_place_anchor: &hello_place_anchor
    parameters:
      env:
        type: enum
        enum: ["Osaka", "Tokyo", "Nagoya"]
        default: "Osaka"
    steps:
      - run:
          command: echo Hello, << parameters.env >>

workflows:
  hello_direct:
    jobs:
      - hello_direct
  hello_use_parameter:
    jobs:
      - hello_use_parameter
  hello_exexutor_commnad:
    jobs:
      - hello_use_executor_command
  hello_enum:
    jobs:
      - hello_use_executor_command_enum:
          name: echo_Osaka
          env: "Osaka"
  hello_use_anchor:
    jobs:
      - hello_use_anchor:
          name: echo_tokyo
          env: "Tokyo"

parameters:
  echoplacename:
    type: string
    default: "Okinawa"

executors:
  hello_executor:
    docker:
      - image: cimg/base:<<parameters.tag>>
    parameters:
      tag:
        default: "2021.07"
        type: string

commands:
  hello_generic_cmd:
    parameters:
      placeName:
        default: "test"
        type: string
    steps:
      - run: echo Hello, <<parameters.placeName>>

jobs:
  hello_direct:
    docker:
        - image: cimg/base:2021.07
    steps:
      - run: echo Hello, "direct"
  
  hello_use_parameter:
    docker:
        - image: cimg/base:2021.07
    steps:
      - run: echo Hello, <<pipeline.parameters.echoplacename>>
  
  hello_use_executor_command:
    executor: hello_executor
    steps:
      - hello_generic_cmd:
          placeName: "tokyo"
          
          
  hello_use_executor_command_enum:
    parameters:
      env:
        type: enum
        enum: ["Osaka", "Tokyo", "Nagoya"]
        default: "Osaka"
    executor:
      name: hello_executor
    steps:
      - run:
          command: echo Hello, << parameters.env >>
  
  hello_use_anchor:
    <<: *hello_palce_anchor
    executor:
      name: hello_executor


